version: '3.8'

volumes:
  postgres_data:
  cache:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: finapp_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: finapp_gotenberg
    command:
      - "gotenberg"
      - "--api-timeout=50s"
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    container_name: finapp_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./config/backups:/backups
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:7.2.1  # bookworm
    container_name: finapp_redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    stdin_open: true
    tty: true
    volumes:
      - cache:/data

