version: '3.7'
name: finapp_auth

volumes:
  postgres_data:

services:

  auth:
    build: ./
    container_name: finapp_auth
    restart: on-failure
    ports:
      - 8005:8005
    environment:
      - PORT=8005
      - KRATOS_URL=http://kratos:4433
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - kratos
  
  postgres:
    image: postgres:15
    container_name: finapp_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DATABASE_NAME},kratos
    ports:
      - 5432:5432
    volumes:
      - ../config/database/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  kratos-migrate:
    image: oryd/kratos:v1.0.0
    container_name: finapp_kratos_db_migrate
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ../config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    image: oryd/kratos:v1.0.0
    container_name: finapp_kratos
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - 4433:4433
      - 4434:4434
    volumes:
      - ../config/kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
