- id: "auth"
  upstream:
    preserve_host: true
    url: "http://api:8005"
    strip_path: /api/v2/auth
  match:
    url: "http://localhost:8080/api/v2/auth/<**>"
    methods:
      - GET
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow

- id: "ws:application"
  upstream:
    preserve_host: true
    url: "http://api:8003"
  match:
    url: "http://localhost:8080/ws"
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: json
