- id: "accounts"
  upstream:
    preserve_host: true
    url: "http://accounts:8001"
    strip_path: /api/v2/accounts
  match:
    url: "http://127.0.0.1:8080/api/v2/accounts/<**>"
    methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/login

- id: "auth"
  upstream:
    preserve_host: true
    url: "http://auth:8005"
  match:
    url: "http://127.0.0.1:8080/api/v2/auth/<**>"
    methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow

- id: "ws:application"
  upstream:
    preserve_host: true
    url: "http://router:8003"
  match:
    url: "http://127.0.0.1:8080/ws"
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: json