name: Create New Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.66.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        BRANCH_HISTORY: full
        INITIAL_VERSION: 1.0.0
